export type LayoutAnimation = {
  type: 'float' | 'bounce' | 'rotate' | 'zoom' | 'zoom-in' | 'zoom-out' | 'zoom-up' | 'zoom-down' | 'slide' | 'slide-up' | 'slide-down' | 'slide-left' | 'slide-right' | 'pulse' | 'swing' | 'shake' | 'spiral' | 'fan' | 'domino' | 'elastic-rotate' | 'converge' | 'diverge' | 'glitch' | 'wobble-3d' | 'rotate-3d' | 'elevator' | 'skew-slide' | 'none';
  duration: number;
  easing: string;
  intensity?: number;
  stagger?: number;
};

export type MediaPosition = 'center' | 'top' | 'bottom' | 'left' | 'right' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export type TextPosition =
  | 'top-left' | 'top-center' | 'top-right'
  | 'center-left' | 'center' | 'center-right'
  | 'bottom-left' | 'bottom-center' | 'bottom-right';

export type TextAnimationType =
  | 'none' | 'fade' | 'blur' | 'zoom-blur' | 'slide-up' | 'slide-down'
  | 'bounce' | 'elastic' | 'typewriter' | 'wave' | 'glitch' | 'flip' | 'scale';

export type DeviceConfig = {
  position: MediaPosition;
  scale: number;
  offsetX: number; // percentage
  offsetY: number; // percentage
  animation: string; // entry animation type
  animateIn: boolean;
};

export type TextConfig = {
  enabled: boolean;
  headline: string;
  tagline: string;
  animation: TextAnimationType;
  position: TextPosition;
  headlineFontSize: number;
  taglineFontSize: number;
  fontFamily: string;
  color: string;
};

export type LayoutPreset = {
  id: string;
  name: string;
  icon: string;
  color: string;
  durationMs: number;
  // Layout animation
  animations: LayoutAnimation[];
  // 3D rotation
  rotationX: number;
  rotationY: number;
  rotationZ: number;
  backgroundGradient: string;
  // Device positioning & animation
  device?: Partial<DeviceConfig>;
  // Text overlay (if present, this is a "text animation" preset)
  text?: Partial<TextConfig>;
  // Category for filtering
  category?: 'layout' | 'text' | 'creative' | 'mockup';
};

// Default configs
export const DEFAULT_DEVICE_CONFIG: DeviceConfig = {
  position: 'center',
  scale: 1,
  offsetX: 0,
  offsetY: 0,
  animation: 'none',
  animateIn: false,
};

export const DEFAULT_TEXT_CONFIG: TextConfig = {
  enabled: false,
  headline: '',
  tagline: '',
  animation: 'none',
  position: 'top-center',
  headlineFontSize: 64,
  taglineFontSize: 24,
  fontFamily: 'Manrope',
  color: '#ffffff',
};

export const LAYOUT_PRESETS: LayoutPreset[] = [
  // --- PREMIUM MOCKUP & SOCIAL ---
  {
    id: 'social-premium-reveal',
    name: 'Premium Reveal',
    icon: '✨',
    color: '#FBBF24',
    durationMs: 4000,
    rotationX: 12,
    rotationY: -15,
    rotationZ: 0,
    backgroundGradient: 'from-slate-950 via-slate-900 to-black',
    animations: [{ type: 'zoom-out', duration: 2000, easing: 'ease-out', intensity: 1.2 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'social-story-drift',
    name: 'Story Drift',
    icon: '📱',
    color: '#EC4899',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -2,
    backgroundGradient: 'from-fuchsia-600 via-pink-500 to-rose-500',
    animations: [{ type: 'float', duration: 5000, easing: 'ease-in-out', intensity: 15 }],
    device: { animation: 'swing-in', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'angular-studio',
    name: 'Angular Studio',
    icon: '📷',
    color: '#6366F1',
    durationMs: 4500,
    rotationX: 25,
    rotationY: 35,
    rotationZ: -5,
    backgroundGradient: 'from-indigo-600 via-violet-600 to-purple-700',
    animations: [{ type: 'wobble-3d', duration: 4500, easing: 'ease-in-out', intensity: 8 }],
    device: { animation: 'rotate-in', animateIn: true, scale: 0.75 },
    category: 'mockup',
  },
  {
    id: 'cinematic-depth',
    name: 'Deep Focus',
    icon: '🎬',
    color: '#DC2626',
    durationMs: 6000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-zinc-900 via-black to-zinc-900',
    animations: [{ type: 'zoom-in', duration: 4000, easing: 'ease-out', intensity: 1.15 }],
    device: { animation: 'fade', animateIn: true, scale: 0.95 },
    category: 'layout',
  },
  {
    id: 'minimal-floating',
    name: 'Clean Float',
    icon: '☁️',
    color: '#F4F4F5',
    durationMs: 4000,
    rotationX: 10,
    rotationY: 10,
    rotationZ: 0,
    backgroundGradient: 'from-slate-50 via-slate-100 to-slate-200',
    animations: [{ type: 'float', duration: 4000, easing: 'ease-in-out', intensity: 20 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'spiral-dynamic',
    name: 'Dynamic Spiral',
    icon: '🌀',
    color: '#8B5CF6',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-600 via-purple-700 to-indigo-800',
    animations: [{ type: 'spiral', duration: 2000, easing: 'ease-out', intensity: 360 }],
    device: { animation: 'spiral-in', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'isometric-hero',
    name: 'Isometric Hero',
    icon: '📐',
    color: '#10B981',
    durationMs: 5000,
    rotationX: 35,
    rotationY: -45,
    rotationZ: 15,
    backgroundGradient: 'from-emerald-500 via-teal-600 to-cyan-700',
    animations: [{ type: 'wobble-3d', duration: 5000, easing: 'ease-in-out', intensity: 5 }],
    device: { animation: 'rise', animateIn: true, scale: 0.7 },
    category: 'mockup',
  },

  // --- TEXT FOCUSED ---
  {
    id: 'text-apple-hero',
    name: 'Keynote Intro',
    icon: '🎤',
    color: '#ffffff',
    durationMs: 4500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 2500, easing: 'ease-out', intensity: 1.1 }],
    device: { animation: 'rise', animateIn: true, scale: 0.75, offsetY: 25 },
    text: { enabled: true, headline: 'iPhone 16 Pro', tagline: 'Built for intelligence.', animation: 'blur', position: 'top-center' },
    category: 'text',
  },
  {
    id: 'text-split-modern',
    name: 'Modern Split',
    icon: '📑',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-700 via-indigo-600 to-violet-700',
    animations: [{ type: 'slide-right', duration: 1000, easing: 'ease-out', intensity: 100 }],
    device: { animation: 'swing-in', animateIn: true, scale: 0.8, offsetX: 25 },
    text: { enabled: true, headline: 'Design Matters', tagline: 'Simplified precision.', animation: 'slide-up', position: 'center-left' },
    category: 'text',
  },
  {
    id: 'text-impact-reveal',
    name: 'Impact Reveal',
    icon: '⚡',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 15,
    rotationY: -10,
    rotationZ: 0,
    backgroundGradient: 'from-slate-950 via-slate-900 to-black',
    animations: [{ type: 'zoom-out', duration: 1500, easing: 'ease-out', intensity: 1.3 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.7, offsetY: 20 },
    text: { enabled: true, headline: 'POWER', tagline: 'Unleashed potential.', animation: 'elastic', position: 'top-center' },
    category: 'text',
  },
  {
    id: 'text-minimal',
    name: 'Minimal',
    icon: '🎯',
    color: '#ffffff',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 via-zinc-800 to-slate-900',
    animations: [{ type: 'zoom-up', duration: 1000, easing: 'ease-out', intensity: 1.1 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.8, offsetX: 0, offsetY: 15, animation: 'fade', animateIn: true },
    text: { enabled: true, headline: 'Think', tagline: 'Different.', animation: 'fade', position: 'top-center', headlineFontSize: 80, taglineFontSize: 32, fontFamily: 'Manrope', color: '#ffffff' },
  },
  {
    id: 'text-hello-again',
    name: 'Hello Again',
    icon: '👋',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-400 via-indigo-400 to-purple-500',
    animations: [{ type: 'float', duration: 3000, easing: 'ease-in-out', intensity: 15 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.7, offsetX: 0, offsetY: 25, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'Hello', tagline: "It's nice to meet you.", animation: 'wave', position: 'top-center', headlineFontSize: 72, taglineFontSize: 24, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Cinematic
  {
    id: 'text-cinema-rise',
    name: 'Cinema Rise',
    icon: '🎬',
    color: '#ffffff',
    durationMs: 4500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 3000, easing: 'ease-out', intensity: 1.1 }],
    category: 'text',
    device: { position: 'top', scale: 0.75, offsetX: 0, offsetY: -20, animation: 'drop', animateIn: true },
    text: { enabled: true, headline: 'Coming Soon', tagline: 'A new era begins.', animation: 'slide-up', position: 'bottom-center', headlineFontSize: 56, taglineFontSize: 22, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Playful
  {
    id: 'text-bounce-pop',
    name: 'Bounce Pop',
    icon: '💥',
    color: '#ffffff',
    durationMs: 2500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-fuchsia-600 via-pink-500 to-rose-500',
    animations: [{ type: 'zoom-out', duration: 600, easing: 'ease-out', intensity: 1.5 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.8, offsetX: 0, offsetY: 15, animation: 'bounce-in', animateIn: true },
    text: { enabled: true, headline: 'POW!', tagline: 'That just happened.', animation: 'bounce', position: 'top-center', headlineFontSize: 96, taglineFontSize: 24, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Tech / Futuristic
  {
    id: 'text-glitch-fx',
    name: 'Glitch FX',
    icon: '🖥️',
    color: '#22d3ee',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-900 via-gray-800 to-black',
    animations: [{ type: 'glitch', duration: 400, easing: 'linear', intensity: 5 }],
    category: 'text',
    device: { position: 'center', scale: 0.9, offsetX: 0, offsetY: 0, animation: 'zoom-in', animateIn: true },
    text: { enabled: true, headline: 'SYSTEM_READY', tagline: '> Initializing...', animation: 'glitch', position: 'center', headlineFontSize: 64, taglineFontSize: 20, fontFamily: 'Manrope', color: '#22d3ee' },
  },
  {
    id: 'text-ai-powered',
    name: 'AI Powered',
    icon: '🤖',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-700 via-purple-600 to-indigo-600',
    animations: [{ type: 'zoom-in', duration: 2000, easing: 'ease-out', intensity: 1.15 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'AI Inside', tagline: 'Intelligent by design.', animation: 'zoom-blur', position: 'top-center', headlineFontSize: 60, taglineFontSize: 22, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Professional
  {
    id: 'text-saas-hero',
    name: 'SaaS Hero',
    icon: '🚀',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-700 via-blue-600 to-cyan-500',
    animations: [{ type: 'slide-right', duration: 900, easing: 'ease-out', intensity: 100 }],
    category: 'text',
    device: { position: 'right', scale: 0.8, offsetX: 25, offsetY: 0, animation: 'slide-left', animateIn: true },
    text: { enabled: true, headline: '10x Faster', tagline: 'Your workflow, supercharged.', animation: 'slide-up', position: 'center-left', headlineFontSize: 56, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Social Media
  {
    id: 'text-story-style',
    name: 'Story Style',
    icon: '📱',
    color: '#ffffff',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-pink-600 via-rose-500 to-red-500',
    animations: [{ type: 'bounce', duration: 700, easing: 'ease-out', intensity: 20 }],
    category: 'text',
    device: { position: 'top', scale: 0.75, offsetX: 0, offsetY: -20, animation: 'drop', animateIn: true },
    text: { enabled: true, headline: 'Swipe Up', tagline: 'Get yours now →', animation: 'elastic', position: 'bottom-center', headlineFontSize: 52, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Countdown / Urgency
  {
    id: 'text-flash-sale',
    name: 'Flash Sale',
    icon: '🏷️',
    color: '#ffffff',
    durationMs: 2500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-600 via-orange-600 to-yellow-500',
    animations: [{ type: 'shake', duration: 600, easing: 'ease-in-out', intensity: 10 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'bounce-in', animateIn: true },
    text: { enabled: true, headline: '50% OFF', tagline: 'Today only!', animation: 'bounce', position: 'top-center', headlineFontSize: 88, taglineFontSize: 28, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // --- MULTI-DEVICE SHOWCASE ---
  {
    id: 'duo-floating-showcase',
    name: 'Duo Floating',
    icon: '👯',
    color: '#8B5CF6',
    durationMs: 4500,
    rotationX: 10,
    rotationY: -15,
    rotationZ: 0,
    backgroundGradient: 'from-violet-900 via-indigo-900 to-black',
    animations: [{ type: 'float', duration: 4500, easing: 'ease-in-out', intensity: 20, stagger: 0.2 }],
    device: { animation: 'swing-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'trio-premium-drift',
    name: 'Trio Showcase',
    icon: '🏘️',
    color: '#3B82F6',
    durationMs: 5000,
    rotationX: 15,
    rotationY: 20,
    rotationZ: -5,
    backgroundGradient: 'from-blue-600 via-indigo-700 to-slate-900',
    animations: [{ type: 'zoom-out', duration: 2500, easing: 'ease-out', intensity: 1.2, stagger: 0.15 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.75 },
    category: 'creative',
  },
  {
    id: 'duo-isometric-rise',
    name: 'Duo Isometric',
    icon: '📐',
    color: '#10B981',
    durationMs: 4000,
    rotationX: 35,
    rotationY: -45,
    rotationZ: 15,
    backgroundGradient: 'from-emerald-600 via-teal-800 to-black',
    animations: [{ type: 'slide-up', duration: 800, easing: 'ease-out', intensity: 60, stagger: 0.3 }],
    device: { animation: 'rise', animateIn: true, scale: 0.75 },
    category: 'mockup',
  },
  {
    id: 'trio-matrix-pop',
    name: 'Matrix Trio',
    icon: '🎰',
    color: '#F43F5E',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-rose-500 via-pink-600 to-purple-700',
    animations: [{ type: 'zoom-in', duration: 800, easing: 'ease-out', intensity: 1.15, stagger: 0.2 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'duo-cinematic-slide',
    name: 'Cinema Duo',
    icon: '🎭',
    color: '#F59E0B',
    durationMs: 5000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-zinc-900 via-black to-zinc-900',
    animations: [{ type: 'slide-right', duration: 1200, easing: 'ease-out', intensity: 120, stagger: 0.4 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'trio-spiral-fan',
    name: 'Fan Trio',
    icon: '🛶',
    color: '#06B6D4',
    durationMs: 4500,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-cyan-500 via-blue-600 to-indigo-900',
    animations: [{ type: 'fan', duration: 1500, easing: 'ease-out', intensity: 30, stagger: 0.3 }],
    device: { animation: 'spiral-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'duo-premium-drift',
    name: 'Duo Drift',
    icon: '🌊',
    color: '#F472B6',
    durationMs: 5000,
    rotationX: 8,
    rotationY: -12,
    rotationZ: 0,
    backgroundGradient: 'from-pink-500 via-purple-600 to-blue-700',
    animations: [{ type: 'slide-right', duration: 6000, easing: 'linear', intensity: 50, stagger: 0.5 }],
    device: { animation: 'swing-in', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'trio-staggered-rise',
    name: 'Trio Rise',
    icon: '⛅',
    color: '#38BDF8',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-400 via-blue-500 to-indigo-600',
    animations: [{ type: 'zoom-up', duration: 1200, easing: 'ease-out', intensity: 1.1, stagger: 0.2 }],
    device: { animation: 'rise', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'trio-mosaic-flow',
    name: 'Mosaic Flow',
    icon: '🧩',
    color: '#818CF8',
    durationMs: 4500,
    rotationX: 5,
    rotationY: 5,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 via-indigo-950 to-black',
    animations: [{ type: 'zoom-out', duration: 2000, easing: 'ease-out', intensity: 1.25, stagger: 0.25 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  // --- ADDITIONAL VARIETY ---
  {
    id: 'duo-pop-staggered',
    name: 'Duo Pop',
    icon: '🗯️',
    color: '#F43F5E',
    durationMs: 3000,
    rotationX: 12,
    rotationY: -10,
    rotationZ: 0,
    backgroundGradient: 'from-rose-500 via-pink-500 to-amber-500',
    animations: [{ type: 'zoom-in', duration: 600, easing: 'ease-out', intensity: 1.2, stagger: 0.2 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'trio-cinema-rise',
    name: 'Cinema Trio',
    icon: '📽️',
    color: '#F59E0B',
    durationMs: 6000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-zinc-900 via-slate-950 to-zinc-900',
    animations: [{ type: 'zoom-in', duration: 4000, easing: 'ease-out', intensity: 1.15, stagger: 0.3 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.75 },
    category: 'layout',
  },
  {
    id: 'duo-drift-clean',
    name: 'Dual Drift',
    icon: '🍃',
    color: '#10B981',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 3,
    backgroundGradient: 'from-emerald-900 via-teal-900 to-black',
    animations: [{ type: 'float', duration: 4000, easing: 'ease-in-out', intensity: 20, stagger: 0.5 }],
    device: { animation: 'swing-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'trio-fan-reveal',
    name: 'Trio Fan',
    icon: '🃏',
    color: '#6366F1',
    durationMs: 4000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-600 via-violet-700 to-slate-900',
    animations: [{ type: 'fan', duration: 1200, easing: 'ease-out', intensity: 45, stagger: 0.2 }],
    device: { animation: 'spiral-in', animateIn: true, scale: 0.7 },
    category: 'creative',
  },
  {
    id: 'duo-slide-impact',
    name: 'Impact Duo',
    icon: '💥',
    color: '#EF4444',
    durationMs: 3000,
    rotationX: 15,
    rotationY: 15,
    rotationZ: -2,
    backgroundGradient: 'from-red-600 via-rose-700 to-black',
    animations: [{ type: 'slide-up', duration: 800, easing: 'ease-out', intensity: 100, stagger: 0.3 }],
    device: { animation: 'drop', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'trio-matrix-vertical',
    name: 'Matrix Vertical',
    icon: '🪜',
    color: '#0EA5E9',
    durationMs: 5000,
    rotationX: 20,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-700 via-blue-800 to-black',
    animations: [{ type: 'slide-down', duration: 1000, easing: 'ease-out', intensity: 80, stagger: 0.2 }],
    device: { animation: 'rise', animateIn: true, scale: 0.75 },
    category: 'layout',
  },
  {
    id: 'minimal-zoom-single',
    name: 'Minimal Zoom',
    icon: '🔍',
    color: '#94A3B8',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-50 to-slate-200',
    animations: [{ type: 'zoom-in', duration: 4000, easing: 'ease-out', intensity: 1.05 }],
    category: 'layout',
  },
  {
    id: 'dramatic-3d-tilt',
    name: 'Dramatic Tilt',
    icon: '📐',
    color: '#F97316',
    durationMs: 5000,
    rotationX: 25,
    rotationY: -25,
    rotationZ: 0,
    backgroundGradient: 'from-orange-500 via-red-600 to-black',
    animations: [{ type: 'wobble-3d', duration: 5000, easing: 'ease-in-out', intensity: 12 }],
    category: 'mockup',
  },
];
