export type LayoutAnimation = {
  type: 'float' | 'bounce' | 'rotate' | 'zoom' | 'zoom-in' | 'zoom-out' | 'zoom-up' | 'zoom-down' | 'slide' | 'slide-up' | 'slide-down' | 'slide-left' | 'slide-right' | 'pulse' | 'swing' | 'shake' | 'spiral' | 'fan' | 'domino' | 'elastic-rotate' | 'converge' | 'diverge' | 'glitch' | 'wobble-3d' | 'rotate-3d' | 'elevator' | 'skew-slide' | 'none';
  duration: number;
  easing: string;
  intensity?: number;
  stagger?: number;
};

export type DevicePosition = 'center' | 'top' | 'bottom' | 'left' | 'right' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export type TextPosition =
  | 'top-left' | 'top-center' | 'top-right'
  | 'center-left' | 'center' | 'center-right'
  | 'bottom-left' | 'bottom-center' | 'bottom-right';

export type TextAnimationType =
  | 'none' | 'fade' | 'blur' | 'zoom-blur' | 'slide-up' | 'slide-down'
  | 'bounce' | 'elastic' | 'typewriter' | 'wave' | 'glitch' | 'flip' | 'scale';

export type DeviceConfig = {
  position: DevicePosition;
  scale: number;
  offsetX: number; // percentage
  offsetY: number; // percentage
  animation: string; // entry animation type
  animateIn: boolean;
};

export type TextConfig = {
  enabled: boolean;
  headline: string;
  tagline: string;
  animation: TextAnimationType;
  position: TextPosition;
  headlineFontSize: number;
  taglineFontSize: number;
  fontFamily: string;
  color: string;
};

export type LayoutPreset = {
  id: string;
  name: string;
  icon: string;
  color: string;
  durationMs: number;
  // Layout animation
  animations: LayoutAnimation[];
  // 3D rotation
  rotationX: number;
  rotationY: number;
  rotationZ: number;
  backgroundGradient: string;
  // Device positioning & animation
  device?: Partial<DeviceConfig>;
  // Text overlay (if present, this is a "text animation" preset)
  text?: Partial<TextConfig>;
  // Category for filtering
  category?: 'layout' | 'text' | 'creative';
};

// Default configs
export const DEFAULT_DEVICE_CONFIG: DeviceConfig = {
  position: 'center',
  scale: 1,
  offsetX: 0,
  offsetY: 0,
  animation: 'none',
  animateIn: false,
};

export const DEFAULT_TEXT_CONFIG: TextConfig = {
  enabled: false,
  headline: '',
  tagline: '',
  animation: 'none',
  position: 'top-center',
  headlineFontSize: 64,
  taglineFontSize: 24,
  fontFamily: 'Manrope',
  color: '#ffffff',
};

export const LAYOUT_PRESETS: LayoutPreset[] = [
  // SINGLE IMAGE - PRESENTATION ANIMATIONS
  // Hero Introductions
  {
    id: 'hero-spotlight',
    name: 'Spotlight',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-950 via-slate-900 to-slate-950',
    icon: 'wb_sunny',
    color: '#FBBF24',
    animations: [
      { type: 'zoom-out', duration: 1500, easing: 'ease-out', intensity: 1.4 },
      { type: 'pulse', duration: 2000, easing: 'ease-in-out', intensity: 1.05 },
    ],
    durationMs: 3000,
  },
  {
    id: 'hero-cinema',
    name: 'Cinematic',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    icon: 'movie',
    color: '#DC2626',
    animations: [{ type: 'zoom-in', duration: 3000, easing: 'ease-out', intensity: 1.15 }],
    durationMs: 3500,
  },
  {
    id: 'hero-rise',
    name: 'Grand Rise',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-amber-900 via-orange-800 to-yellow-700',
    icon: 'trending_up',
    color: '#F97316',
    animations: [{ type: 'zoom-up', duration: 1400, easing: 'ease-out', intensity: 1.2 }],
    durationMs: 2500,
  },

  // Energetic Entrances
  {
    id: 'pop-entrance',
    name: 'Pop!',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-fuchsia-600 via-pink-500 to-rose-500',
    icon: 'celebration',
    color: '#EC4899',
    animations: [
      { type: 'zoom-out', duration: 600, easing: 'ease-out', intensity: 1.5 },
      { type: 'bounce', duration: 800, easing: 'ease-out', intensity: 12 },
    ],
    durationMs: 2000,
  },
  {
    id: 'bounce-drop',
    name: 'Drop In',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-600 via-purple-600 to-indigo-600',
    icon: 'download',
    color: '#8B5CF6',
    animations: [{ type: 'zoom-down', duration: 1000, easing: 'ease-out', intensity: 1.15 }],
    durationMs: 2000,
  },
  {
    id: 'spring-up',
    name: 'Spring Up',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-emerald-500 via-green-500 to-teal-500',
    icon: 'north',
    color: '#10B981',
    animations: [
      { type: 'slide-up', duration: 800, easing: 'ease-out', intensity: 80 },
      { type: 'bounce', duration: 600, easing: 'ease-out', intensity: 10 },
    ],
    durationMs: 2200,
  },

  // Slide Presentations
  {
    id: 'slide-power',
    name: 'Power Slide',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-700 via-blue-600 to-cyan-500',
    icon: 'trending_flat',
    color: '#3B82F6',
    animations: [{ type: 'slide-right', duration: 900, easing: 'ease-out', intensity: 120 }],
    durationMs: 1800,
  },
  {
    id: 'slide-reveal',
    name: 'Curtain',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-rose-700 via-red-600 to-orange-500',
    icon: 'open_in_full',
    color: '#F43F5E',
    animations: [{ type: 'slide-left', duration: 900, easing: 'ease-out', intensity: 120 }],
    durationMs: 1800,
  },

  // Atmospheric Effects
  {
    id: 'float-dream',
    name: 'Dreamy',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-400 via-indigo-400 to-purple-500',
    icon: 'cloud',
    color: '#38BDF8',
    animations: [{ type: 'float', duration: 3000, easing: 'ease-in-out', intensity: 20 }],
    durationMs: 4000,
  },
  {
    id: 'float-orbit',
    name: 'Orbit',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-900 via-purple-900 to-slate-900',
    icon: 'public',
    color: '#6366F1',
    animations: [
      { type: 'float', duration: 2500, easing: 'ease-in-out', intensity: 15 },
      { type: 'rotate', duration: 8000, easing: 'linear', intensity: 360 },
    ],
    durationMs: 8000,
  },
  {
    id: 'heartbeat',
    name: 'Heartbeat',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-600 via-rose-600 to-pink-600',
    icon: 'favorite',
    color: '#EF4444',
    animations: [{ type: 'pulse', duration: 800, easing: 'ease-in-out', intensity: 1.12 }],
    durationMs: 2500,
  },

  // Dynamic Effects
  {
    id: 'meteor-impact',
    name: 'Meteor',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-950 via-orange-950 to-slate-950',
    icon: 'local_fire_department',
    color: '#F97316',
    animations: [
      { type: 'zoom-down', duration: 400, easing: 'ease-in', intensity: 1.8 },
      { type: 'bounce', duration: 600, easing: 'ease-out', intensity: 25 },
    ],
    durationMs: 2000,
  },
  {
    id: 'neon-flicker',
    name: 'Neon Flicker',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-purple-950 to-black',
    icon: 'fluorescent',
    color: '#E879F9',
    animations: [
      { type: 'glitch', duration: 200, easing: 'linear', intensity: 3 },
      { type: 'pulse', duration: 800, easing: 'ease-in-out', intensity: 1.08 },
    ],
    durationMs: 2500,
  },

  // Attention Grabbers
  {
    id: 'shake-alert',
    name: 'Alert!',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-600 via-orange-600 to-yellow-500',
    icon: 'warning',
    color: '#EA580C',
    animations: [{ type: 'shake', duration: 600, easing: 'ease-in-out', intensity: 10 }],
    durationMs: 1500,
  },
  {
    id: 'swing-playful',
    name: 'Playful',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-lime-500 via-green-500 to-emerald-500',
    icon: 'mood',
    color: '#84CC16',
    animations: [{ type: 'swing', duration: 1200, easing: 'ease-in-out', intensity: 12 }],
    durationMs: 2500,
  },

  // DUAL IMAGE - PRESENTATION ANIMATIONS
  {
    id: 'duo-versus',
    name: 'VS Battle',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-700 via-gray-900 to-blue-700',
    icon: 'compare',
    color: '#DC2626',
    animations: [
      { type: 'slide-left', duration: 800, easing: 'ease-out', intensity: 100 },
      { type: 'slide-right', duration: 800, easing: 'ease-out', intensity: 100 },
    ],
    durationMs: 2500,
  },
  {
    id: 'duo-transform',
    name: 'Transform',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-700 via-purple-600 to-fuchsia-600',
    icon: 'auto_awesome',
    color: '#9333EA',
    animations: [{ type: 'zoom-out', duration: 1000, easing: 'ease-out', intensity: 1.3 }],
    durationMs: 2500,
  },
  {
    id: 'duo-cascade',
    name: 'Cascade',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-800 via-indigo-700 to-violet-700',
    icon: 'waterfall_chart',
    color: '#4F46E5',
    animations: [{ type: 'slide-down', duration: 800, easing: 'ease-out', intensity: 80 }],
    durationMs: 2500,
  },
  {
    id: 'duo-wave',
    name: 'Wave',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-cyan-600 via-blue-600 to-indigo-600',
    icon: 'waves',
    color: '#0891B2',
    animations: [{ type: 'slide-up', duration: 700, easing: 'ease-out', intensity: 70 }],
    durationMs: 2200,
  },
  {
    id: 'duo-sync-pop',
    name: 'Sync Pop',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-pink-600 via-rose-500 to-red-500',
    icon: 'interests',
    color: '#EC4899',
    animations: [{ type: 'zoom-out', duration: 800, easing: 'ease-out', intensity: 1.4 }],
    durationMs: 2000,
  },
  {
    id: 'duo-dance',
    name: 'Dance',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-amber-500 via-orange-500 to-red-500',
    icon: 'sports_esports',
    color: '#F59E0B',
    animations: [{ type: 'bounce', duration: 700, easing: 'ease-out', intensity: 20 }],
    durationMs: 2200,
  },
  {
    id: 'duo-spotlight',
    name: 'Twin Lights',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 via-zinc-800 to-slate-900',
    icon: 'flare',
    color: '#FBBF24',
    animations: [{ type: 'zoom-up', duration: 1000, easing: 'ease-out', intensity: 1.2 }],
    durationMs: 2500,
  },
  {
    id: 'duo-bounce-alt',
    name: 'Ping Pong',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-lime-500 via-green-500 to-teal-500',
    icon: 'sports_tennis',
    color: '#84CC16',
    animations: [
      { type: 'bounce', duration: 600, easing: 'ease-out', intensity: 25 },
      { type: 'swing', duration: 1000, easing: 'ease-in-out', intensity: 8 },
    ],
    durationMs: 2500,
  },
  {
    id: 'duo-float-sync',
    name: 'Float Pair',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-purple-600 via-violet-600 to-indigo-600',
    icon: 'bubble_chart',
    color: '#A855F7',
    animations: [{ type: 'float', duration: 2500, easing: 'ease-in-out', intensity: 18 }],
    durationMs: 4000,
  },

  // TRIO IMAGES - SEQUENTIAL & STAGGERED ANIMATIONS
  {
    id: 'trio-cascade-fall',
    name: 'Cascade Fall',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-900 via-purple-800 to-pink-700',
    icon: 'stacked_bar_chart',
    color: '#A855F7',
    animations: [{ type: 'slide-down', duration: 600, easing: 'ease-out', intensity: 100, stagger: 200 }],
    durationMs: 2500,
  },
  {
    id: 'trio-domino',
    name: 'Domino',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 via-zinc-800 to-neutral-900',
    icon: 'view_column',
    color: '#64748B',
    animations: [{ type: 'domino', duration: 800, easing: 'ease-out', intensity: 15, stagger: 150 }],
    durationMs: 2800,
  },
  {
    id: 'trio-pop-sequence',
    name: 'Pop Sequence',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-rose-600 via-pink-500 to-fuchsia-500',
    icon: 'bubble_chart',
    color: '#EC4899',
    animations: [{ type: 'zoom-out', duration: 500, easing: 'ease-out', intensity: 1.5, stagger: 180 }],
    durationMs: 2200,
  },
  {
    id: 'trio-wave-rise',
    name: 'Wave Rise',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-cyan-600 via-teal-500 to-emerald-500',
    icon: 'waves',
    color: '#14B8A6',
    animations: [{ type: 'slide-up', duration: 700, easing: 'ease-out', intensity: 120, stagger: 150 }],
    durationMs: 2600,
  },
  {
    id: 'trio-fan-out',
    name: 'Fan Out',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-amber-600 via-orange-500 to-red-500',
    icon: 'open_with',
    color: '#F59E0B',
    animations: [{ type: 'fan', duration: 900, easing: 'ease-out', intensity: 30, stagger: 120 }],
    durationMs: 2500,
  },
  {
    id: 'trio-spiral-in',
    name: 'Spiral In',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-700 via-purple-600 to-indigo-600',
    icon: 'rotate_right',
    color: '#7C3AED',
    animations: [{ type: 'spiral', duration: 1000, easing: 'ease-out', intensity: 360, stagger: 200 }],
    durationMs: 3000,
  },
  {
    id: 'trio-bounce-chain',
    name: 'Bounce Chain',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-lime-500 via-green-500 to-emerald-600',
    icon: 'sports_basketball',
    color: '#84CC16',
    animations: [{ type: 'bounce', duration: 600, easing: 'ease-out', intensity: 30, stagger: 200 }],
    durationMs: 2400,
  },
  {
    id: 'trio-swing-parade',
    name: 'Swing Parade',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-yellow-500 via-amber-500 to-orange-500',
    icon: 'emoji_people',
    color: '#FBBF24',
    animations: [{ type: 'swing', duration: 800, easing: 'ease-in-out', intensity: 20, stagger: 180 }],
    durationMs: 2800,
  },
  {
    id: 'trio-spotlight-reveal',
    name: 'Spotlight Reveal',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    icon: 'flare',
    color: '#FBBF24',
    animations: [
      { type: 'zoom-up', duration: 800, easing: 'ease-out', intensity: 1.3, stagger: 250 },
      { type: 'pulse', duration: 600, easing: 'ease-in-out', intensity: 1.08 },
    ],
    durationMs: 3200,
  },
  {
    id: 'trio-slide-stack',
    name: 'Stack Up',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-700 via-blue-600 to-cyan-500',
    icon: 'layers',
    color: '#3B82F6',
    animations: [{ type: 'slide-up', duration: 600, easing: 'ease-out', intensity: 150, stagger: 180 }],
    durationMs: 2400,
  },
  {
    id: 'trio-scatter',
    name: 'Scatter',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-fuchsia-600 via-pink-600 to-rose-600',
    icon: 'scatter_plot',
    color: '#D946EF',
    animations: [
      { type: 'slide-left', duration: 500, easing: 'ease-out', intensity: 80, stagger: 100 },
      { type: 'slide-right', duration: 500, easing: 'ease-out', intensity: 80, stagger: 100 },
    ],
    durationMs: 2000,
  },

  // NEW CREATIVE PRESETS
  {
    id: 'hero-glitch',
    name: 'Cyber Glitch',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-900 via-gray-800 to-black',
    icon: 'broken_image',
    color: '#22d3ee',
    animations: [
      { type: 'glitch', duration: 400, easing: 'linear', intensity: 5 },
      { type: 'zoom-in', duration: 200, easing: 'ease-out', intensity: 1.05 },
    ],
    durationMs: 2000,
  },
  {
    id: 'duo-converge',
    name: 'Magnetic',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-500 via-purple-500 to-pink-500',
    icon: 'join_inner',
    color: '#818cf8',
    animations: [{ type: 'converge', duration: 800, easing: 'ease-out', intensity: 100 }],
    durationMs: 2500,
  },
  {
    id: 'trio-wobble',
    name: '3D Float',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-teal-400 via-emerald-400 to-green-400',
    icon: '3d_rotation',
    color: '#34d399',
    animations: [{ type: 'wobble-3d', duration: 2000, easing: 'ease-in-out', intensity: 10, stagger: 300 }],
    durationMs: 4000,
  },
  {
    id: 'quad-elastic',
    name: 'Elastic Grid',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-orange-400 via-red-400 to-pink-400',
    icon: 'grid_view',
    color: '#fb923c',
    animations: [
      { type: 'elastic-rotate', duration: 1200, easing: 'ease-out', intensity: 5, stagger: 100 },
      { type: 'zoom-in', duration: 800, easing: 'ease-out', intensity: 1.1, stagger: 100 },
    ],
    durationMs: 3000,
  },

  // Cinematic & Presentation
  {
    id: 'morphic-shift',
    name: 'Morphic',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-950 via-slate-900 to-violet-950',
    icon: 'transform',
    color: '#818CF8',
    animations: [
      { type: 'skew-slide', duration: 800, easing: 'ease-out', intensity: 15 },
      { type: 'zoom-in', duration: 1200, easing: 'ease-out', intensity: 1.15 },
    ],
    durationMs: 2500,
  },
  {
    id: 'vortex-zoom',
    name: 'Vortex',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-cyan-950 to-black',
    icon: 'cyclone',
    color: '#22D3EE',
    animations: [
      { type: 'spiral', duration: 1200, easing: 'ease-out', intensity: 180 },
      { type: 'zoom-out', duration: 800, easing: 'ease-out', intensity: 1.3 },
    ],
    durationMs: 2500,
  },
  {
    id: 'gravity-pull',
    name: 'Gravity',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-950 via-blue-950 to-slate-950',
    icon: 'compress',
    color: '#3B82F6',
    animations: [
      { type: 'converge', duration: 600, easing: 'ease-in', intensity: 80 },
      { type: 'elastic-rotate', duration: 800, easing: 'ease-out', intensity: 8 },
    ],
    durationMs: 2200,
  },
  {
    id: 'present-elevator',
    name: 'Elevator Pitch',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-emerald-900 via-green-900 to-black',
    icon: 'elevator',
    color: '#4ade80',
    animations: [{ type: 'elevator', duration: 1500, easing: 'ease-out', intensity: 1 }],
    durationMs: 2500,
  },
  {
    id: 'present-skew',
    name: 'Dynamic Skew',
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-purple-900 via-fuchsia-900 to-black',
    icon: 'bolt',
    color: '#d8b4fe',
    animations: [{ type: 'skew-slide', duration: 1200, easing: 'ease-out', intensity: 30 }],
    durationMs: 2000,
  },

  // =============================================================================
  // TEXT ANIMATION PRESETS
  // =============================================================================
  // Apple-Style Hero Intros
  {
    id: 'text-apple-intro',
    name: 'Apple Intro',
    icon: '',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 2000, easing: 'ease-out', intensity: 1.1 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'iPhone 16 Pro', tagline: 'Built for Apple Intelligence.', animation: 'blur', position: 'top-center', headlineFontSize: 64, taglineFontSize: 24, fontFamily: 'Manrope', color: '#ffffff' },
  },
  {
    id: 'text-keynote',
    name: 'Keynote',
    icon: '🎤',
    color: '#ffffff',
    durationMs: 4500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 2500, easing: 'ease-out', intensity: 1.15 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.7, offsetX: 0, offsetY: 25, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'This is iPhone', tagline: 'The best iPhone ever made.', animation: 'zoom-blur', position: 'top-center', headlineFontSize: 72, taglineFontSize: 28, fontFamily: 'Manrope', color: '#ffffff' },
  },
  {
    id: 'text-pro-reveal',
    name: 'Pro Reveal',
    icon: '⚡',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-950 via-slate-900 to-black',
    animations: [{ type: 'zoom-out', duration: 1500, easing: 'ease-out', intensity: 1.3 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'bounce-in', animateIn: true },
    text: { enabled: true, headline: 'Pro', tagline: 'Beyond professional.', animation: 'elastic', position: 'top-center', headlineFontSize: 96, taglineFontSize: 24, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // App Store Style
  {
    id: 'text-app-feature',
    name: 'App Feature',
    icon: '📱',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-600 via-purple-600 to-indigo-600',
    animations: [{ type: 'bounce', duration: 800, easing: 'ease-out', intensity: 15 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.8, offsetX: 0, offsetY: 15, animation: 'bounce-in', animateIn: true },
    text: { enabled: true, headline: 'App of the Day', tagline: 'Discover something new.', animation: 'bounce', position: 'top-center', headlineFontSize: 48, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  {
    id: 'text-launch-day',
    name: 'Launch Day',
    icon: '🚀',
    color: '#ffffff',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-emerald-500 via-green-500 to-teal-500',
    animations: [{ type: 'slide-up', duration: 800, easing: 'ease-out', intensity: 80 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'Available Now', tagline: 'Download on the App Store.', animation: 'elastic', position: 'top-center', headlineFontSize: 60, taglineFontSize: 22, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Dramatic Reveals
  {
    id: 'text-one-more-thing',
    name: 'One More Thing',
    icon: '✨',
    color: '#ffffff',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 3000, easing: 'ease-out', intensity: 1.2 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.65, offsetX: 0, offsetY: 30, animation: 'fade', animateIn: true },
    text: { enabled: true, headline: 'One more thing...', tagline: '', animation: 'typewriter', position: 'top-center', headlineFontSize: 56, taglineFontSize: 0, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Split Layouts
  {
    id: 'text-split-left',
    name: 'Split Left',
    icon: '◀️',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-700 via-blue-600 to-cyan-500',
    animations: [{ type: 'slide-right', duration: 900, easing: 'ease-out', intensity: 120 }],
    category: 'text',
    device: { position: 'right', scale: 0.8, offsetX: 25, offsetY: 0, animation: 'slide-left', animateIn: true },
    text: { enabled: true, headline: 'Beautiful Design', tagline: 'Crafted with care.', animation: 'slide-up', position: 'center-left', headlineFontSize: 48, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  {
    id: 'text-split-right',
    name: 'Split Right',
    icon: '▶️',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-rose-700 via-red-600 to-orange-500',
    animations: [{ type: 'slide-left', duration: 900, easing: 'ease-out', intensity: 120 }],
    category: 'text',
    device: { position: 'left', scale: 0.8, offsetX: -25, offsetY: 0, animation: 'slide-right', animateIn: true },
    text: { enabled: true, headline: 'Next Level', tagline: 'Experience the difference.', animation: 'slide-up', position: 'center-right', headlineFontSize: 48, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Minimal & Clean
  {
    id: 'text-minimal',
    name: 'Minimal',
    icon: '🎯',
    color: '#ffffff',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 via-zinc-800 to-slate-900',
    animations: [{ type: 'zoom-up', duration: 1000, easing: 'ease-out', intensity: 1.1 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.8, offsetX: 0, offsetY: 15, animation: 'fade', animateIn: true },
    text: { enabled: true, headline: 'Think', tagline: 'Different.', animation: 'fade', position: 'top-center', headlineFontSize: 80, taglineFontSize: 32, fontFamily: 'Manrope', color: '#ffffff' },
  },
  {
    id: 'text-hello-again',
    name: 'Hello Again',
    icon: '👋',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-400 via-indigo-400 to-purple-500',
    animations: [{ type: 'float', duration: 3000, easing: 'ease-in-out', intensity: 15 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.7, offsetX: 0, offsetY: 25, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'Hello', tagline: "It's nice to meet you.", animation: 'wave', position: 'top-center', headlineFontSize: 72, taglineFontSize: 24, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Cinematic
  {
    id: 'text-cinema-rise',
    name: 'Cinema Rise',
    icon: '🎬',
    color: '#ffffff',
    durationMs: 4500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 3000, easing: 'ease-out', intensity: 1.1 }],
    category: 'text',
    device: { position: 'top', scale: 0.75, offsetX: 0, offsetY: -20, animation: 'drop', animateIn: true },
    text: { enabled: true, headline: 'Coming Soon', tagline: 'A new era begins.', animation: 'slide-up', position: 'bottom-center', headlineFontSize: 56, taglineFontSize: 22, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Playful
  {
    id: 'text-bounce-pop',
    name: 'Bounce Pop',
    icon: '💥',
    color: '#ffffff',
    durationMs: 2500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-fuchsia-600 via-pink-500 to-rose-500',
    animations: [{ type: 'zoom-out', duration: 600, easing: 'ease-out', intensity: 1.5 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.8, offsetX: 0, offsetY: 15, animation: 'bounce-in', animateIn: true },
    text: { enabled: true, headline: 'POW!', tagline: 'That just happened.', animation: 'bounce', position: 'top-center', headlineFontSize: 96, taglineFontSize: 24, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Tech / Futuristic
  {
    id: 'text-glitch-fx',
    name: 'Glitch FX',
    icon: '🖥️',
    color: '#22d3ee',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-900 via-gray-800 to-black',
    animations: [{ type: 'glitch', duration: 400, easing: 'linear', intensity: 5 }],
    category: 'text',
    device: { position: 'center', scale: 0.9, offsetX: 0, offsetY: 0, animation: 'zoom-in', animateIn: true },
    text: { enabled: true, headline: 'SYSTEM_READY', tagline: '> Initializing...', animation: 'glitch', position: 'center', headlineFontSize: 64, taglineFontSize: 20, fontFamily: 'Manrope', color: '#22d3ee' },
  },
  {
    id: 'text-ai-powered',
    name: 'AI Powered',
    icon: '🤖',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-700 via-purple-600 to-indigo-600',
    animations: [{ type: 'zoom-in', duration: 2000, easing: 'ease-out', intensity: 1.15 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'rise', animateIn: true },
    text: { enabled: true, headline: 'AI Inside', tagline: 'Intelligent by design.', animation: 'zoom-blur', position: 'top-center', headlineFontSize: 60, taglineFontSize: 22, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Professional
  {
    id: 'text-saas-hero',
    name: 'SaaS Hero',
    icon: '🚀',
    color: '#ffffff',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-blue-700 via-blue-600 to-cyan-500',
    animations: [{ type: 'slide-right', duration: 900, easing: 'ease-out', intensity: 100 }],
    category: 'text',
    device: { position: 'right', scale: 0.8, offsetX: 25, offsetY: 0, animation: 'slide-left', animateIn: true },
    text: { enabled: true, headline: '10x Faster', tagline: 'Your workflow, supercharged.', animation: 'slide-up', position: 'center-left', headlineFontSize: 56, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Social Media
  {
    id: 'text-story-style',
    name: 'Story Style',
    icon: '📱',
    color: '#ffffff',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-pink-600 via-rose-500 to-red-500',
    animations: [{ type: 'bounce', duration: 700, easing: 'ease-out', intensity: 20 }],
    category: 'text',
    device: { position: 'top', scale: 0.75, offsetX: 0, offsetY: -20, animation: 'drop', animateIn: true },
    text: { enabled: true, headline: 'Swipe Up', tagline: 'Get yours now →', animation: 'elastic', position: 'bottom-center', headlineFontSize: 52, taglineFontSize: 20, fontFamily: 'Manrope', color: '#ffffff' },
  },
  // Countdown / Urgency
  {
    id: 'text-flash-sale',
    name: 'Flash Sale',
    icon: '🏷️',
    color: '#ffffff',
    durationMs: 2500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-600 via-orange-600 to-yellow-500',
    animations: [{ type: 'shake', duration: 600, easing: 'ease-in-out', intensity: 10 }],
    category: 'text',
    device: { position: 'bottom', scale: 0.75, offsetX: 0, offsetY: 20, animation: 'bounce-in', animateIn: true },
    text: { enabled: true, headline: '50% OFF', tagline: 'Today only!', animation: 'bounce', position: 'top-center', headlineFontSize: 88, taglineFontSize: 28, fontFamily: 'Manrope', color: '#ffffff' },
  },
];
