export type LayoutAnimation = {
  type: 'float' | 'bounce' | 'rotate' | 'zoom' | 'zoom-in' | 'zoom-out' | 'zoom-up' | 'zoom-down' | 'slide' | 'slide-up' | 'slide-down' | 'slide-left' | 'slide-right' | 'pulse' | 'swing' | 'shake' | 'spiral' | 'fan' | 'domino' | 'elastic-rotate' | 'converge' | 'diverge' | 'glitch' | 'wobble-3d' | 'rotate-3d' | 'elevator' | 'skew-slide' | 'orbit' | 'reveal-3d' | 'float-complex' | 'pulse-3d' | 'parallax-drift' | 'reveal-zoom' | 'magnetic' | 'none' | 'camera-pan' | 'hero-float' | 'cinematic-zoom' | 'soft-drift' | 'elastic-enter' | 'stagger-fade' | 'perspective-twist' | 'depth-hover' | 'scatter' | 'wave' | 'breathe' | 'spotlight' | 'confetti' | 'scanline' | 'grain' | 'stack-drop' | 'hover' | 'search-light' | 'scan-vertical' | 'snow-fall' | 'heat-wave' | 'leaf-fall' | 'hver';
  duration: number;
  easing: string;
  intensity?: number;
  stagger?: number;
};

export type MediaPosition = 'center' | 'top' | 'bottom' | 'left' | 'right' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export type TextPosition =
  | 'top-left' | 'top-center' | 'top-right'
  | 'center-left' | 'center' | 'center-right'
  | 'bottom-left' | 'bottom-center' | 'bottom-right';

export type TextAnimationType =
  | 'none' | 'fade' | 'blur' | 'zoom-blur' | 'slide-up' | 'slide-down'
  | 'bounce' | 'elastic' | 'typewriter' | 'wave' | 'glitch' | 'flip' | 'scale'
  | 'shimmer' | 'glitch-rgb' | 'reveal-split' | 'mask-reveal' | 'perspective-3d'
  | 'blur-reveal' | 'expand-letter' | 'strobe' | 'float-drift';

export type DeviceConfig = {
  type: string;
  position: MediaPosition;
  scale: number;
  offsetX: number; // percentage
  offsetY: number;
  animation: string; // entry animation type
  animateIn: boolean;
};

export type TextConfig = {
  enabled: boolean;
  headline: string;
  tagline: string;
  animation: TextAnimationType;
  position: TextPosition;
  headlineFontSize: number;
  taglineFontSize: number;
  fontFamily: string;
  color: string;
};

export type LayoutPreset = {
  id: string;
  name: string;
  icon: string;
  color: string;
  durationMs: number;
  // Layout animation
  animations: LayoutAnimation[];
  // 3D rotation
  rotationX: number;
  rotationY: number;
  rotationZ: number;
  backgroundGradient: string;
  // Device positioning & animation
  device?: Partial<DeviceConfig>;
  // Text overlay (if present, this is a "text animation" preset)
  text?: Partial<TextConfig>;
  // Category for filtering
  category?: 'layout' | 'text' | 'creative' | 'mockup';
};

// Default configs
export const DEFAULT_DEVICE_CONFIG: DeviceConfig = {
  type: 'iphone-16-pro',
  position: 'center',
  scale: 1,
  offsetX: 0,
  offsetY: 0,
  animation: 'none',
  animateIn: false,
};

export const DEFAULT_TEXT_CONFIG: TextConfig = {
  enabled: false,
  headline: '',
  tagline: '',
  animation: 'none',
  position: 'top-center',
  headlineFontSize: 64,
  taglineFontSize: 24,
  fontFamily: 'Manrope',
  color: '#ffffff',
};

export const LAYOUT_PRESETS: LayoutPreset[] = [
  // --- ESSENTIALS (CLEAN & SIMPLE) ---
  {
    id: 'clean-zoom-in',
    name: 'Clean Zoom In',
    icon: 'magnifying-glass-plus',
    color: '#3B82F6',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-50 to-slate-200',
    animations: [{ type: 'zoom-in', duration: 4000, easing: 'ease-out', intensity: 1.1, stagger: 0.2 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'clean-zoom-out',
    name: 'Clean Zoom Out',
    icon: 'magnifying-glass-minus',
    color: '#60A5FA',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-100 to-white',
    animations: [{ type: 'zoom-out', duration: 4000, easing: 'ease-out', intensity: 1.1, stagger: 0.2 }],
    device: { animation: 'fade', animateIn: true, scale: 0.95 },
    category: 'layout',
  },
  {
    id: 'clean-fade-up',
    name: 'Fade Up',
    icon: 'arrow-up',
    color: '#94A3B8',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-50 to-gray-100',
    animations: [{ type: 'slide-up', duration: 1500, easing: 'ease-out', intensity: 20, stagger: 0.15 }],
    device: { animation: 'rise', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'soft-float',
    name: 'Soft Float',
    icon: 'cloud',
    color: '#A78BFA',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-50 to-blue-50',
    animations: [{ type: 'float', duration: 5000, easing: 'ease-in-out', intensity: 15, stagger: 0.3 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },

  // --- DIRECTIONAL (SLIDES) ---
  {
    id: 'slide-from-left',
    name: 'Slide Right',
    icon: 'arrow-right',
    color: '#F59E0B',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 5,
    rotationZ: 0,
    backgroundGradient: 'from-amber-50 to-orange-50',
    animations: [{ type: 'slide-right', duration: 1000, easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)', intensity: 100, stagger: 0.1 }],
    device: { animation: 'slide-right', animateIn: true, scale: 0.85 },
    category: 'layout',
  },
  {
    id: 'slide-from-right',
    name: 'Slide Left',
    icon: 'arrow-left',
    color: '#F59E0B',
    durationMs: 3500,
    rotationX: 0,
    rotationY: -5,
    rotationZ: 0,
    backgroundGradient: 'from-orange-50 to-amber-50',
    animations: [{ type: 'slide-left', duration: 1000, easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)', intensity: 100, stagger: 0.1 }],
    device: { animation: 'slide-left', animateIn: true, scale: 0.85 },
    category: 'layout',
  },
  {
    id: 'slide-drop-in',
    name: 'Drop In',
    icon: 'arrow-down',
    color: '#EF4444',
    durationMs: 3000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-50 to-rose-100',
    animations: [{ type: 'slide-down', duration: 800, easing: 'ease-out', intensity: 50, stagger: 0.15 }],
    device: { animation: 'drop', animateIn: true, scale: 0.9 },
    category: 'layout',
  },

  // --- POP & BOUNCE (DYNAMIC) ---
  {
    id: 'bouncy-pop',
    name: 'Bouncy Pop',
    icon: 'party-popper',
    color: '#EC4899',
    durationMs: 3000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-pink-100 to-rose-200',
    animations: [{ type: 'bounce', duration: 1000, easing: 'ease-out', intensity: 1.5, stagger: 0.1 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'elastic-rise',
    name: 'Elastic Rise',
    icon: 'spring',
    color: '#10B981',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-emerald-50 to-teal-100',
    animations: [{ type: 'slide-up', duration: 1200, easing: 'elastic', intensity: 30, stagger: 0.15 }],
    device: { animation: 'rise', animateIn: true, scale: 0.85 },
    category: 'creative',
  },

  // --- PREMIUM & CINEMATIC ---
  {
    id: 'premium-reveal',
    name: 'Premium Reveal',
    icon: 'sparkles',
    color: '#FBBF24',
    durationMs: 4500,
    rotationX: 5,
    rotationY: -5,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 via-slate-800 to-black',
    animations: [{ type: 'zoom-out', duration: 2500, easing: 'ease-out', intensity: 1.15, stagger: 0.2 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'cinematic-drift',
    name: 'Cinematic Drift',
    icon: 'film',
    color: '#8B5CF6',
    durationMs: 6000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -2,
    backgroundGradient: 'from-zinc-900 via-black to-zinc-900',
    animations: [{ type: 'float-complex', duration: 6000, easing: 'ease-in-out', intensity: 10, stagger: 0.4 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'studio-clean',
    name: 'Studio Clean',
    icon: 'camera',
    color: '#6366F1',
    durationMs: 4000,
    rotationX: 10,
    rotationY: 10,
    rotationZ: 0,
    backgroundGradient: 'from-gray-100 to-gray-200',
    animations: [{ type: 'wobble-3d', duration: 4000, easing: 'ease-in-out', intensity: 2, stagger: 0.2 }],
    device: { animation: 'rotate-in', animateIn: true, scale: 0.85 },
    category: 'mockup',
  },

  // --- CREATIVE 3D ---
  {
    id: 'isometric-view',
    name: 'Isometric',
    icon: 'cube',
    color: '#10B981',
    durationMs: 4000,
    rotationX: 25,
    rotationY: -25,
    rotationZ: 10,
    backgroundGradient: 'from-teal-500 via-emerald-600 to-green-700',
    animations: [{ type: 'slide-up', duration: 1000, easing: 'ease-out', intensity: 40, stagger: 0.2 }],
    device: { animation: 'rise', animateIn: true, scale: 0.75 },
    category: 'mockup',
  },
  {
    id: 'spiral-showcase',
    name: 'Spiral',
    icon: 'hurricane',
    color: '#8B5CF6',
    durationMs: 4500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-600 via-purple-700 to-fuchsia-800',
    animations: [{ type: 'spiral', duration: 1500, easing: 'ease-out', intensity: 180, stagger: 0.15 }],
    device: { animation: 'spiral-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'fan-deck',
    name: 'Fan Deck',
    icon: 'cards',
    color: '#06B6D4',
    durationMs: 4000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-cyan-500 via-blue-600 to-indigo-900',
    animations: [{ type: 'fan', duration: 1200, easing: 'ease-out', intensity: 25, stagger: 0.1 }],
    device: { animation: 'spiral-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'orbit-flow',
    name: 'Orbit Flow',
    icon: 'planet',
    color: '#A855F7',
    durationMs: 5000,
    rotationX: 15,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-purple-900 via-fuchsia-900 to-black',
    animations: [{ type: 'orbit', duration: 5000, easing: 'linear', intensity: 30, stagger: 0.2 }],
    device: { animation: 'reveal-zoom', animateIn: true, scale: 0.8 },
    category: 'creative',
  },

  // --- TEXT FOCUSED (Kept as specific use cases) ---
  {
    id: 'text-intro',
    name: 'Text Intro',
    icon: 'type',
    color: '#ffffff',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-black via-zinc-900 to-black',
    animations: [{ type: 'zoom-in', duration: 3000, easing: 'ease-out', intensity: 1.05, stagger: 0.1 }],
    device: { animation: 'rise', animateIn: true, scale: 0.75, offsetY: 25 },
    text: { enabled: true, headline: 'Showcase', tagline: 'Your masterpiece.', animation: 'blur', position: 'top-center' },
    category: 'text',
  },
  {
    id: 'text-impact',
    name: 'Text Impact',
    icon: 'lightning',
    color: '#ffffff',
    durationMs: 3000,
    rotationX: 10,
    rotationY: -5,
    rotationZ: 0,
    backgroundGradient: 'from-red-900 via-black to-black',
    animations: [{ type: 'zoom-out', duration: 800, easing: 'ease-out', intensity: 1.2, stagger: 0.1 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.8 },
    text: { enabled: true, headline: 'IMPACT', tagline: 'Make it count.', animation: 'elastic', position: 'center' },
    category: 'text',
  }
  ,
  // --- NORDIC / MINIMAL ---
  {
    id: 'nordic-air',
    name: 'Nordic Air',
    icon: 'wind',
    color: '#E2E8F0',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-50 via-slate-100 to-white',
    animations: [{ type: 'soft-drift', duration: 5000, easing: 'ease-in-out', intensity: 5, stagger: 0.5 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'finnish-mist',
    name: 'Finnish Mist',
    icon: 'cloud-fog',
    color: '#CBD5E1',
    durationMs: 4500,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-100 via-zinc-100 to-stone-100',
    animations: [{ type: 'zoom-in', duration: 4500, easing: 'ease-out', intensity: 1.05, stagger: 0.2 }],
    device: { animation: 'rise', animateIn: true, scale: 0.85 },
    category: 'layout',
  },
  {
    id: 'copenhagen-clean',
    name: 'Copenhagen',
    icon: 'store',
    color: '#94A3B8',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 10,
    rotationZ: 0,
    backgroundGradient: 'from-white via-slate-50 to-white',
    animations: [{ type: 'slide-up', duration: 1200, easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)', intensity: 30, stagger: 0.1 }],
    device: { animation: 'parallax-3d', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'arctic-white',
    name: 'Arctic',
    icon: 'snowflake',
    color: '#F8FAFC',
    durationMs: 4000,
    rotationX: 2,
    rotationY: -2,
    rotationZ: 0,
    backgroundGradient: 'from-sky-50 to-white',
    animations: [{ type: 'float', duration: 4000, easing: 'ease-in-out', intensity: 8, stagger: 0.3 }],
    device: { animation: 'fade', animateIn: true, scale: 0.95 },
    category: 'layout',
  },
  {
    id: 'stockholm-studio',
    name: 'Stockholm',
    icon: 'camera-movie',
    color: '#475569',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-50 to-slate-200',
    animations: [{ type: 'camera-pan', duration: 5000, easing: 'linear', intensity: 10, stagger: 0 }],
    device: { animation: 'zoom-in', animateIn: true, scale: 0.9 },
    category: 'mockup',
  },
  
  // --- NATURE / ORGANIC ---
  {
    id: 'forest-canopy',
    name: 'Canopy',
    icon: 'tree-pine',
    color: '#059669',
    durationMs: 5000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-green-50 to-emerald-100',
    animations: [{ type: 'float-complex', duration: 5000, easing: 'ease-in-out', intensity: 12, stagger: 0.4 }],
    device: { animation: 'rise', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'ocean-depth',
    name: 'Deep Ocean',
    icon: 'waves',
    color: '#0369A1',
    durationMs: 6000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-cyan-900 via-blue-900 to-slate-900',
    animations: [{ type: 'depth-hover', duration: 6000, easing: 'ease-in-out', intensity: 20, stagger: 0.3 }],
    device: { animation: 'fade', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'desert-dune',
    name: 'Dunes',
    icon: 'mountain',
    color: '#D97706',
    durationMs: 5000,
    rotationX: 15,
    rotationY: 5,
    rotationZ: -2,
    backgroundGradient: 'from-orange-100 via-amber-100 to-yellow-50',
    animations: [{ type: 'soft-drift', duration: 5000, easing: 'ease-in-out', intensity: 15, stagger: 0.2 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.8 },
    category: 'layout',
  },
  {
    id: 'alpine-rise',
    name: 'Alpine',
    icon: 'mountain-snow',
    color: '#3B82F6',
    durationMs: 4000,
    rotationX: -5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-indigo-50 to-white',
    animations: [{ type: 'slide-up', duration: 2000, easing: 'active', intensity: 50, stagger: 0.1 }],
    device: { animation: 'rise', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'savanna-sun',
    name: 'Savanna',
    icon: 'sun',
    color: '#F59E0B',
    durationMs: 4500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-yellow-100 via-orange-100 to-red-50',
    animations: [{ type: 'zoom-in', duration: 4500, easing: 'ease-out', intensity: 1.1, stagger: 0.1 }],
    device: { animation: 'fade', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'rainforest-mist',
    name: 'Rainforest',
    icon: 'droplets',
    color: '#10B981',
    durationMs: 5000,
    rotationX: 5,
    rotationY: 5,
    rotationZ: 0,
    backgroundGradient: 'from-teal-900 to-emerald-900',
    animations: [{ type: 'float', duration: 3000, easing: 'ease-in-out', intensity: 10, stagger: 0.2 }],
    device: { animation: 'reveal-zoom', animateIn: true, scale: 0.8 },
    category: 'creative',
  },

  // --- COSMIC / SPACE ---
  {
    id: 'nebula-drift',
    name: 'Nebula',
    icon: 'sparkles',
    color: '#8B5CF6',
    durationMs: 8000,
    rotationX: 10,
    rotationY: 10,
    rotationZ: 5,
    backgroundGradient: 'from-purple-900 via-indigo-900 to-black',
    animations: [{ type: 'float-complex', duration: 8000, easing: 'linear', intensity: 20, stagger: 0.5 }],
    device: { animation: 'fade', animateIn: true, scale: 0.75 },
    category: 'creative',
  },
  {
    id: 'quasar-pulse',
    name: 'Quasar',
    icon: 'activity',
    color: '#EF4444',
    durationMs: 2000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-900 to-black',
    animations: [{ type: 'pulse-3d', duration: 2000, easing: 'ease-in-out', intensity: 1.05, stagger: 0.1 }],
    device: { animation: 'zoom-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'gravity-well',
    name: 'Gravity',
    icon: 'magnet',
    color: '#6366F1',
    durationMs: 4000,
    rotationX: 20,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-900 to-black',
    animations: [{ type: 'converge', duration: 4000, easing: 'ease-in-out', intensity: 50, stagger: 0.1 }],
    device: { animation: 'magnetic', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'orbital-ring',
    name: 'Orbital',
    icon: 'circle-dashed',
    color: '#A855F7',
    durationMs: 6000,
    rotationX: 15,
    rotationY: 0,
    rotationZ: 15,
    backgroundGradient: 'from-fuchsia-900 via-purple-900 to-black',
    animations: [{ type: 'orbit', duration: 6000, easing: 'linear', intensity: 20, stagger: 0.2 }],
    device: { animation: 'reveal-zoom', animateIn: true, scale: 0.7 },
    category: 'creative',
  },
  {
    id: 'star-field',
    name: 'Star Field',
    icon: 'stars',
    color: '#FFF',
    durationMs: 10000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'bg-black',
    animations: [{ type: 'zoom-in', duration: 10000, easing: 'linear', intensity: 1.5, stagger: 0.5 }],
    device: { animation: 'fade', animateIn: true, scale: 0.8 },
    category: 'creative',
  },

  // --- URBAN / STREET ---
  {
    id: 'tokyo-neon',
    name: 'Tokyo Neon',
    icon: 'zap',
    color: '#EC4899',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 20,
    rotationZ: 0,
    backgroundGradient: 'from-pink-900 via-purple-900 to-slate-900',
    animations: [{ type: 'glitch', duration: 3000, easing: 'steps(5)', intensity: 10, stagger: 0.1 }],
    device: { animation: 'slide-right', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'berlin-concrete',
    name: 'Berlin',
    icon: 'building',
    color: '#64748B',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-400 via-gray-400 to-zinc-400',
    animations: [{ type: 'slide-up', duration: 1000, easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)', intensity: 50, stagger: 0.05 }],
    device: { animation: 'rise', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'nyc-grid',
    name: 'NYC Grid',
    icon: 'layout-grid',
    color: '#334155',
    durationMs: 4000,
    rotationX: 5,
    rotationY: -5,
    rotationZ: 0,
    backgroundGradient: 'from-slate-100 to-gray-200',
    animations: [{ type: 'stagger-fade', duration: 1500, easing: 'ease-out', intensity: 20, stagger: 0.1 }],
    device: { animation: 'zoom-in', animateIn: true, scale: 0.85 },
    category: 'layout',
  },
  {
    id: 'cyber-punk',
    name: 'Cyberpunk',
    icon: 'cpu',
    color: '#FACC15',
    durationMs: 3000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 5,
    backgroundGradient: 'from-yellow-400 via-yellow-600 to-black',
    animations: [{ type: 'skew-slide', duration: 800, easing: 'active', intensity: 20, stagger: 0.05 }],
    device: { animation: 'wobble-3d', animateIn: true, scale: 0.8 },
    category: 'creative',
  },

  // --- GLASS / CRYSTAL ---
  {
    id: 'frosted-glass',
    name: 'Frosted',
    icon: 'mouse-pointer-2',
    color: '#A7F3D0',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-emerald-50 via-teal-50 to-cyan-50',
    animations: [{ type: 'blur-reveal', duration: 2000, easing: 'ease-out', intensity: 10, stagger: 0.2 }],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'prism-refract',
    name: 'Prism',
    icon: 'triangle',
    color: '#F472B6',
    durationMs: 4000,
    rotationX: 15,
    rotationY: 15,
    rotationZ: 0,
    backgroundGradient: 'from-pink-100 via-purple-100 to-indigo-100',
    animations: [{ type: 'rotate-3d', duration: 4000, easing: 'ease-in-out', intensity: 15, stagger: 0.2 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'crystal-clear',
    name: 'Crystal',
    icon: 'diamond',
    color: '#38BDF8',
    durationMs: 5000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-50 to-blue-100',
    animations: [{ type: 'cinematic-zoom', duration: 5000, easing: 'ease-out', intensity: 1.05, stagger: 0.1 }],
    device: { animation: 'zoom-in', animateIn: true, scale: 0.85 },
    category: 'layout',
  },

  // --- TECH / MODERN ---
  {
    id: 'silicon-valley',
    name: 'Silicon',
    icon: 'microchip',
    color: '#6366F1',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-50 to-gray-100',
    animations: [{ type: 'slide-up', duration: 1000, easing: 'ease-out', intensity: 30, stagger: 0.1 }],
    device: { animation: 'rise', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'quantum-state',
    name: 'Quantum',
    icon: 'atom',
    color: '#8B5CF6',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-violet-50 to-white',
    animations: [{ type: 'elastic-enter', duration: 2000, easing: 'elastic', intensity: 1.2, stagger: 0.1 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.85 },
    category: 'creative',
  },
  {
    id: 'hero-grid',
    name: 'Hero Grid',
    icon: 'layout-template',
    color: '#475569',
    durationMs: 4000,
    rotationX: 20,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-slate-100 to-slate-200',
    animations: [{ type: 'perspective-twist', duration: 4000, easing: 'ease-in-out', intensity: 10, stagger: 0.1 }],
    device: { animation: 'tilt-reveal', animateIn: true, scale: 0.8 },
    category: 'mockup',
  },

  // --- ABSTRACT / ART ---
  {
    id: 'geometric-chaos',
    name: 'Chaos',
    icon: 'shapes',
    color: '#F43F5E',
    durationMs: 3500,
    rotationX: 10,
    rotationY: 10,
    rotationZ: 10,
    backgroundGradient: 'from-rose-100 to-orange-100',
    animations: [{ type: 'scatter', duration: 1500, easing: 'ease-out', intensity: 100, stagger: 0.1 } as any],
    device: { animation: 'wobble-3d', animateIn: true, scale: 0.75 },
    category: 'creative',
  },
  {
    id: 'ordered-flux',
    name: 'Flux',
    icon: 'git-merge',
    color: '#0EA5E9',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 5,
    rotationZ: 0,
    backgroundGradient: 'from-sky-100 to-blue-100',
    animations: [{ type: 'wave', duration: 4000, easing: 'ease-in-out', intensity: 20, stagger: 0.2 } as any],
    device: { animation: 'swing-in', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'minimal-zen',
    name: 'Zen',
    icon: 'circle-dot',
    color: '#78716C',
    durationMs: 6000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-stone-50 to-stone-100',
    animations: [{ type: 'breathe', duration: 6000, easing: 'ease-in-out', intensity: 1.02, stagger: 0.5 } as any],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },

  // --- APPLE / SHOWCASE ---
  {
    id: 'keynote-black',
    name: 'Keynote',
    icon: 'presentation',
    color: '#000',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'bg-black',
    animations: [{ type: 'hero-float', duration: 3000, easing: 'ease-out', intensity: 20, stagger: 0.1 }],
    device: { animation: 'rise', animateIn: true, scale: 0.85 },
    category: 'text',
  },
  {
    id: 'product-hero-x',
    name: 'Product X',
    icon: 'smartphone',
    color: '#333',
    durationMs: 4000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-900 to-black',
    animations: [{ type: 'zoom-in', duration: 1000, easing: 'ease-out', intensity: 1.2, stagger: 0 }],
    device: { animation: 'drop', animateIn: true, scale: 0.9 },
    category: 'mockup',
  },
  {
    id: 'cupertino-stage',
    name: 'Stage',
    icon: 'mic-2',
    color: '#555',
    durationMs: 5000,
    rotationX: 2,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-800 to-gray-900',
    animations: [{ type: 'spotlight', duration: 5000, easing: 'ease-out', intensity: 1, stagger: 0 } as any],
    device: { animation: 'fade', animateIn: true, scale: 0.8 },
    category: 'mockup',
  },
  {
    id: 'event-reveal',
    name: 'Event',
    icon: 'calendar-star',
    color: '#D946EF',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-fuchsia-100 to-pink-100',
    animations: [{ type: 'confetti', duration: 3000, easing: 'ease-out', intensity: 1, stagger: 0.1 } as any],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.85 },
    category: 'creative',
  },

  // --- VINTAGE / RETRO ---
  {
    id: 'retro-sunset',
    name: 'Sunset',
    icon: 'sunset',
    color: '#F97316',
    durationMs: 4000,
    rotationX: 5,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-orange-400 via-red-500 to-purple-600',
    animations: [{ type: 'scanline', duration: 4000, easing: 'linear', intensity: 10, stagger: 0.1 } as any],
    device: { animation: 'rise', animateIn: true, scale: 0.8 },
    category: 'creative',
  },
  {
    id: 'vintage-cream',
    name: 'Cream',
    icon: 'coffee',
    color: '#FDE68A',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 2,
    backgroundGradient: 'from-yellow-50 to-amber-50',
    animations: [{ type: 'grain', duration: 5000, easing: 'linear', intensity: 5, stagger: 0 } as any],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'polaroid-stack',
    name: 'Polaroid',
    icon: 'image',
    color: '#FFF',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 5,
    backgroundGradient: 'from-gray-100 to-white',
    animations: [{ type: 'stack-drop', duration: 2000, easing: 'active', intensity: 30, stagger: 0.2 } as any],
    device: { animation: 'drop', animateIn: true, scale: 0.8 },
    category: 'mockup',
  },
  
  // --- BOLD / EDITORIAL ---
  {
    id: 'bold-magazine',
    name: 'Magazine',
    icon: 'book-open',
    color: '#000',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-white to-gray-50',
    text: { enabled: true, headline: 'BOLD', tagline: 'Statement.', animation: 'tracking-in-expand', position: 'center' },
    animations: [{ type: 'slide-up', duration: 1500, easing: 'ease-out', intensity: 20, stagger: 0.1 }],
    device: { animation: 'zoom-in', animateIn: true, scale: 0.8 },
    category: 'text',
  },
  {
    id: 'typography-focus',
    name: 'Type',
    icon: 'pilcrow',
    color: '#333',
    durationMs: 3500,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'bg-white',
    text: { enabled: true, headline: 'Aa', tagline: 'Typography matters.', animation: 'blur-in-expand', position: 'center-left' },
    animations: [{ type: 'fade', duration: 1000, easing: 'ease-out', intensity: 1, stagger: 0 }],
    device: { animation: 'slide-left', animateIn: true, scale: 0.8 },
    category: 'text',
  },
  {
    id: 'fashion-edit',
    name: 'Fashion',
    icon: 'shirt',
    color: '#EC4899',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 5,
    rotationZ: 0,
    backgroundGradient: 'from-pink-50 to-rose-50',
    text: { enabled: true, headline: 'STYLE', tagline: 'Summer Collection', animation: 'hero-reveal', position: 'bottom-center' },
    animations: [{ type: 'hover', duration: 4000, easing: 'ease-in-out', intensity: 10, stagger: 0.1 } as any],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'text',
  }
  ,
  // --- CINEMATIC ---
  {
    id: 'hollywood-premiere',
    name: 'Premiere',
    icon: 'clapperboard',
    color: '#E11D48',
    durationMs: 5000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-rose-900 to-black',
    animations: [{ type: 'spotlight', duration: 5000, easing: 'ease-out', intensity: 1, stagger: 0 } as any],
    device: { animation: 'zoom-in', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'noir-detective',
    name: 'Noir',
    icon: 'search',
    color: '#52525B',
    durationMs: 6000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-gray-800 to-black',
    animations: [{ type: 'search-light', duration: 6000, easing: 'linear', intensity: 1, stagger: 0 } as any],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'sci-fi-scanner',
    name: 'Scanner',
    icon: 'scan',
    color: '#06B6D4',
    durationMs: 3000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-cyan-900 to-black',
    animations: [{ type: 'scan-vertical', duration: 3000, easing: 'linear', intensity: 1, stagger: 0 } as any],
    device: { animation: 'glitch', animateIn: true, scale: 0.85 } as any,
    category: 'creative',
  },

  // --- SPORTS / ENERGY ---
  {
    id: 'energy-rush',
    name: 'Energy',
    icon: 'activity',
    color: '#EAB308',
    durationMs: 2000,
    rotationX: 10,
    rotationY: -10,
    rotationZ: 5,
    backgroundGradient: 'from-yellow-400 to-orange-600',
    animations: [{ type: 'shake', duration: 500, easing: 'active', intensity: 20, stagger: 0.05 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'speed-demon',
    name: 'Speed',
    icon: 'gauge',
    color: '#DC2626',
    durationMs: 1500,
    rotationX: 0,
    rotationY: 20,
    rotationZ: 0,
    backgroundGradient: 'from-red-600 to-red-900',
    animations: [{ type: 'slide-right', duration: 800, easing: 'active', intensity: 100, stagger: 0.05 }],
    device: { animation: 'slide-right', animateIn: true, scale: 0.9 },
    category: 'layout',
  },
  {
    id: 'active-life',
    name: 'Active',
    icon: 'heart-pulse',
    color: '#22C55E',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-green-400 to-emerald-600',
    animations: [{ type: 'pulse', duration: 1000, easing: 'ease-in-out', intensity: 1.1, stagger: 0.1 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.85 },
    category: 'layout',
  },

  // --- FOOD / FRESH ---
  {
    id: 'fresh-organic',
    name: 'Organic',
    icon: 'leaf',
    color: '#84CC16',
    durationMs: 5000,
    rotationX: 5,
    rotationY: 5,
    rotationZ: 0,
    backgroundGradient: 'from-lime-50 to-green-100',
    animations: [{ type: 'float', duration: 3000, easing: 'ease-in-out', intensity: 5, stagger: 0.2 }],
    device: { animation: 'rise', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'spicy-heat',
    name: 'Spicy',
    icon: 'flame',
    color: '#EF4444',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-red-100 to-orange-100',
    animations: [{ type: 'wobble-3d', duration: 2000, easing: 'ease-in-out', intensity: 5, stagger: 0.1 }],
    device: { animation: 'shake', animateIn: true, scale: 0.85 } as any,
    category: 'creative',
  },
  {
    id: 'sweet-treat',
    name: 'Sweet',
    icon: 'candy',
    color: '#F472B6',
    durationMs: 4000,
    rotationX: 10,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-pink-100 to-rose-200',
    animations: [{ type: 'bounce', duration: 1000, easing: 'active', intensity: 1.2, stagger: 0.1 }],
    device: { animation: 'bounce-in', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  
  // --- HOLIDAY / SEASONAL ---
  {
    id: 'winter-wonder',
    name: 'Winter',
    icon: 'snowflake',
    color: '#E0F2FE',
    durationMs: 5000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-sky-100 to-blue-50',
    animations: [{ type: 'snow-fall', duration: 5000, easing: 'linear', intensity: 1, stagger: 0.2 } as any],
    device: { animation: 'fade', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'summer-vibes',
    name: 'Summer',
    icon: 'sun-medium',
    color: '#FDBA74',
    durationMs: 4000,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    backgroundGradient: 'from-orange-200 to-yellow-200',
    animations: [{ type: 'heat-wave', duration: 4000, easing: 'ease-in-out', intensity: 5, stagger: 0.1 } as any],
    device: { animation: 'rise', animateIn: true, scale: 0.9 },
    category: 'creative',
  },
  {
    id: 'autumn-drift',
    name: 'Autumn',
    icon: 'wind',
    color: '#F59E0B',
    durationMs: 5000,
    rotationX: 5,
    rotationY: 5,
    rotationZ: 2,
    backgroundGradient: 'from-amber-100 to-orange-100',
    animations: [{ type: 'leaf-fall', duration: 5000, easing: 'ease-in-out', intensity: 10, stagger: 0.3 } as any],
    device: { animation: 'hover', animateIn: true, scale: 0.85 } as any,
    category: 'creative',
  }
];
